#!/usr/bin/env python3

import os
import sys

newargs = []

# Find executable
exe_file = None
for path in os.environ["PATH"].split(os.pathsep):
    exe_file = os.path.join(path, sys.argv[1])
    if os.path.isfile(exe_file) and os.access(exe_file, os.X_OK):
        break
if exe_file is not None:
    newargs.append( exe_file )
else:
    newargs.append( sys.argv[1] )

# Rewrite arguments
newargs.append( sys.argv[2] )
for x in sys.argv[2:]:
    if ( x[0] == '+' ):
        newargs.append( '--testplusarg' )
        newargs.append( x )
    elif ( x == '-l' ):
        newargs.append( '--log' )
    else:
        newargs.append( x )

# Run the updated command
os.execv( newargs[0], newargs )
sys.exit(-1)

